// The workspace README. Dual-audience: humans browsing the folder, and agents that
// need to work out what the workspace is and how to drive it. Deps: ./host.js

import { host } from './host.js';

// ── Workspace README ────────────────────────────────────────
// Dual-audience: humans browsing the folder AND AI agents (like OpenClaw)
// that need to understand what this workspace is and how to operate it.
// How a run proceeds, what the agent is allowed to touch, and how automation drives
// it. Split from workspaceReadme purely to keep either half readable.
// Static tour of the generated layout: what each file and directory is for. Only the
// active-agent markers vary, so it lives apart from the configuration summary.
const fileGuide = (a) => `## File Guide

### You Edit These

| File | Purpose |
|------|---------|
| \`xswarm-qa.config.json5\` | All settings: site URL, agent type, schedule, notifications. Extensively commented. |
| \`.env.local\` | Auth credentials (gitignored — never committed). |
| \`check-and-run.sh\` | Entry point script. Usually no edits needed. |

### AI Agent Instructions

Each supported agent has its own instruction file. The active agent is set in
\`xswarm-qa.config.json5\` under \`agent.type\`. All configs are installed — switching
agents requires only a config edit, no reinstallation.

| File | Agent | Status |
|------|-------|--------|
| \`.claude/QA.md\` | Claude Code | ${a.agent === 'claude-code' ? '**Active**' : 'Installed'} |
| \`.gemini/QA.md\` | Gemini CLI | ${a.agent === 'gemini-cli' ? '**Active**' : 'Installed'} |
| \`.codex/QA.md\` | Codex | ${a.agent === 'codex' ? '**Active**' : 'Installed'} |
| \`.local/QA.md\` | Local AI (Ollama, etc.) | ${a.agent === 'local-ai' ? '**Active** (needs custom setup)' : 'Template'} |

### Infrastructure (Managed)

| Path | Purpose |
|------|---------|
| \`.xswarm-qa/version.txt\` | Installed xSwarm QA version |
| \`.xswarm-qa/tools/\` | Helper scripts (update detection, notifications) |
| \`.xswarm-qa/db/\` | Issue tracking database (future: libSQL + vectors) |
| \`.xswarm-qa/cache/\` | Page snapshots, content hashes |

### Session Output

Each QA run creates a timestamped folder in \`runs/\`:

\`\`\`
runs/2025-06-15_14-30-00/
├── report.md          Human-readable audit report
├── summary.json       Machine-readable results
├── screenshots/       Evidence images
└── session.log        Full agent conversation
\`\`\`

---
`;

const operationsGuide = (a, h) => `## How It Works

1. \`check-and-run.sh\` checks if the site has changed (strategy: \`${a.strategy}\`)
2. If changes detected (or \`--force\`), creates a session folder in \`runs/\`
3. Invokes the configured AI agent with the QA instructions
4. Agent explores the site, tests scenarios across viewports and input modes
5. Agent writes report, screenshots, and summary to the session folder
6. Notification sent (if configured)

### Safety Model

The AI agent operates under strict constraints defined in the QA.md files:

- **Writes only** to \`runs/<session>/\` — everything else is read-only
- **Never** submits destructive forms, creates real data, or triggers emails
- **Never** accesses areas beyond test credentials
- **60-minute hard cap** on session duration
- All constraints enforced regardless of autonomous/yolo mode

---

## For OpenClaw / Automation

This workspace is designed for unattended operation. Key integration points:

- **Entry point**: \`./check-and-run.sh\` (exit 0 = success, exit 1 = no changes)
- **Force run**: \`./check-and-run.sh --force\` (skip update detection)
- **Results**: \`runs/<latest>/summary.json\` for machine-readable output
- **Notifications**: Configured in \`xswarm-qa.config.json5\` → \`notifications\` section
- **Signal file**: If notification type is \`file-signal\`, check for \`.signal\` file after run

### Cron Example

\`\`\`bash
# Run QA daily at 3am
0 3 * * * cd ${a.folderName || h + '-qa'} && ./check-and-run.sh >> /var/log/xswarm-qa.log 2>&1
\`\`\`

---

## Updating xSwarm QA

\`\`\`bash
npx xswarm-qa ${a.folderName || '.'}
\`\`\`

Running the installer on an existing workspace will offer to update the infrastructure
(\`.xswarm-qa/\`, agent configs) while preserving your settings, credentials, and reports.

---

## Links

- **xSwarm QA**: [xswarm.ai](https://xswarm.ai)
- **Source**: [github.com/chadananda/xswarm-qa](https://github.com/chadananda/xswarm-qa)
- **Issues**: [github.com/chadananda/xswarm-qa/issues](https://github.com/chadananda/xswarm-qa/issues)
`;

export const workspaceReadme = (a, version) => {
  const h = host(a.url);
  return `# ${h} — xSwarm QA Workspace

> **Autonomous AI quality assurance for [${h}](${a.url})**
> Generated by [xSwarm QA](https://xswarm.ai) v${version}

---

## What Is This?

This folder is a self-contained QA workspace. AI agents (Claude Code, Gemini CLI,
Codex, or local models) read the instructions here to autonomously test ${a.url},
then write session reports to \`runs/\`.

**No code integration required.** The agent navigates via URL, tests like a real
user, and produces professional audit reports.

---

## Quick Reference

| Action | Command |
|--------|---------|
| Run a QA session | \`./check-and-run.sh\` |
| Force run (skip update check) | \`./check-and-run.sh --force\` |
| Edit settings | \`$EDITOR xswarm-qa.config.json5\` |
| Edit credentials | \`$EDITOR .env.local\` |
| View latest report | \`ls -t runs/*/report.md \\| head -1\` |

---

${fileGuide(a)}
## Current Configuration

| Setting | Value |
|---------|-------|
| Site | ${a.url} |
| Domains | ${a.domains || 'none'} |
| Auth | ${a.authMode === 'auth' ? `Enabled (${a.loginUrl})` : 'Audit only (public pages)'} |
| Update detection | ${a.strategy} |
| Schedule | ${a.frequency}${a.rapidDev ? ' (rapid development mode)' : ''} |
| Agent | ${a.agent} |
${a.openclaw ? `| OpenClaw | Cron: \`${a.cronSchedule}\`${a.openclawNotify ? ', notify on report' : ''} |` : ''}

---

${operationsGuide(a, h)}`;
};
