// The config is generated by interpolating answers into a JSON5 document, and read back
// by three separate tools. Anything that makes it unparseable takes the whole workspace
// down at once — config-get, check-update and notify all fail together.
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync } from 'child_process';
import { mkdtemp, rm, readFile, writeFile } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { generate } from '../src/generate.js';

let sandbox;
let n = 0;

beforeAll(async () => { sandbox = await mkdtemp(join(tmpdir(), 'xswarm-qa-esc-')); });
afterAll(async () => { await rm(sandbox, { recursive: true, force: true }); });

const build = async (over = {}) => {
  const dir = join(sandbox, `w${n++}`);
  await generate(dir, {
    url: 'https://example.com', authMode: 'audit', loginUrl: '', username: '', authPassword: '',
    strategy: 'manual', strategyConfig: {}, agent: 'claude-code',
    openclaw: false, cronSchedule: '', openclawNotify: false,
    focus: ['seo'], depth: 'standard', frequency: 'daily', ...over,
  }, { dryRun: false, version: 'test' });
  return dir;
};

const get = (dir, path) =>
  execFileSync(process.execPath, ['.xswarm-qa/tools/config-get.js', path],
    { cwd: dir, encoding: 'utf8' }).trim();

describe('values that must survive into the config', () => {
  // A double quote used to close the JSON string early and corrupt the document.
  it.each([
    ['a double quote', 'https://ex.com/path"quote'],
    ['two double quotes', 'https://ex.com/a"b"c'],
    ['a backslash', 'https://ex.com/back\\slash'],
    ['a glob', 'https://example.com/*'],
    ['a comment closer in a query', 'https://ex.com/?q=1&x=*/'],
    ['a newline', 'https://ex.com/a\nb'],
  ])('round-trips a url containing %s', async (_label, url) => {
    const dir = await build({ url });
    expect(get(dir, 'site.url')).toBe(url);
  });

  it('round-trips a login url containing a quote', async () => {
    const dir = await build({ authMode: 'auth', loginUrl: 'https://ex.com/log"in', username: 'u', authPassword: 'p' });
    expect(get(dir, 'auth.loginUrl')).toBe('https://ex.com/log"in');
  });

  it('round-trips a cron expression containing a quote', async () => {
    const dir = await build({ openclaw: true, cronSchedule: '0 3 * * * "x' });
    expect(get(dir, 'openclaw.cronSchedule')).toBe('0 3 * * * "x');
  });
});

describe('the reader', () => {
  it('does not treat a quote inside a comment as the start of a string', async () => {
    const dir = await build();
    const p = join(dir, 'xswarm-qa.config.json5');
    const cfg = await readFile(p, 'utf8');
    // An odd number of quotes in a comment used to swallow the rest of the file.
    await writeFile(p, cfg.replace('{', '{\n  // a user note: it"s fine\n'), 'utf8');
    expect(get(dir, 'site.url')).toBe('https://example.com');
  });

  it('still ignores a real comment that looks like config', async () => {
    const dir = await build();
    const p = join(dir, 'xswarm-qa.config.json5');
    const cfg = await readFile(p, 'utf8');
    await writeFile(p, cfg.replace('{', '{\n  // "site": { "url": "https://evil.example" },\n'), 'utf8');
    expect(get(dir, 'site.url')).toBe('https://example.com');
  });
});
